export const generalQuestions = [
  {
    id: 1,
    question: "What country does Brie cheese originate from?",
    correctAnswer: "France",
    options: ["France", "Italy", "Switzerland", "Spain"],
  },
  {
    id: 2,
    question: "Who ordered the construction of El Capricho Park in Madrid?",
    correctAnswer: "The Duchess of Osuna",
    options: [
      "The Duchess of Osuna",
      "King Carlos III",
      "Francisco de Goya",
      "Isabel II",
    ],
  },
  {
    id: 3,
    question: "What is the currency of Mexico?",
    correctAnswer: "Mexican Peso",
    options: ["Mexican Peso", "Dollar", "Sol", "Euro"],
  },
  {
    id: 4,
    question: "In what year was Heinz founded?",
    correctAnswer: "1869",
    options: ["1850", "1869", "1900", "1895"],
  },
  {
    id: 5,
    question: "What colors are on the flag of Japan?",
    correctAnswer: "White and red",
    options: [
      "White and red",
      "Red and black",
      "Blue and white",
      "White and green",
    ],
  },
  {
    id: 6,
    question: "What four ingredients are needed to prepare a Cosmopolitan?",
    correctAnswer: "Lime juice, vodka, cranberry juice, cointreau",
    options: [
      "Lime juice, vodka, cranberry juice, cointreau",
      "Rum, pineapple juice, lime, sugar",
      "Tequila, lemon, sugar, sparkling water",
      "Whiskey, lemon, water, mint syrup",
    ],
  },
  {
    id: 7,
    question: "In which city was the first Fashion Week held?",
    correctAnswer: "New York",
    options: ["Paris", "London", "New York", "Milan"],
  },
  {
    id: 8,
    question: "What nut is inside a Ferrero Rocher?",
    correctAnswer: "Hazelnut",
    options: ["Almond", "Hazelnut", "Pistachio", "Walnut"],
  },
  {
    id: 9,
    question: "What are baby rabbits called?",
    correctAnswer: "Kittens",
    options: ["Bunnies", "Kittens", "Lambs", "Piglets"],
  },
  {
    id: 10,
    question: "In what year did David Delfín die?",
    correctAnswer: "2017",
    options: ["2017", "2015", "2019", "2020"],
  },
  {
    id: 11,
    question: "How many valves does a human heart have?",
    correctAnswer: "Four: mitral, tricuspid, aortic, and pulmonary",
    options: [
      "Three: mitral, aortic, and pulmonary",
      "Four: mitral, tricuspid, aortic, and pulmonary",
      "Five: mitral, tricuspid, aortic, pulmonary, and venous",
      "Three: mitral, pulmonary, and tricuspid",
    ],
  },
  {
    id: 12,
    question: "What was the last name of Queen Elizabeth II of England?",
    correctAnswer: "Windsor",
    options: ["Tudor", "Windsor", "Stuart", "Lancaster"],
  },
  {
    id: 13,
    question: "What is the real name of the Mexican Venice?",
    correctAnswer: "Xochimilco",
    options: ["Chichen Itza", "Xochimilco", "Tulum", "Cancun"],
  },
  {
    id: 14,
    question: "What day is the Hispanic Day celebration?",
    correctAnswer: "October 12th",
    options: ["May 1st", "October 12th", "December 25th", "September 15th"],
  },
  {
    id: 15,
    question: "What was the name of Frida Kahlo's husband?",
    correctAnswer: "Diego Rivera",
    options: [
      "Diego Rivera",
      "David Alfaro Siqueiros",
      "José Clemente Orozco",
      "Vicente Rojo",
    ],
  },
  {
    id: 16,
    question: "Who invented the light bulb?",
    correctAnswer: "Thomas Edison",
    options: [
      "Nikola Tesla",
      "Thomas Edison",
      "Alexander Graham Bell",
      "Guglielmo Marconi",
    ],
  },
  {
    id: 17,
    question:
      "Regarding its size, what is the most powerful muscle in the human body?",
    correctAnswer: "The masseter",
    options: [
      "The heart",
      "The gluteus maximus",
      "The masseter",
      "The quadriceps muscle",
    ],
  },
  {
    id: 18,
    question: "What is the name of the bread with chorizo typical of Asturias?",
    correctAnswer: "Bollo preñao",
    options: [
      "Bollo preñao",
      "Asturian sandwich",
      "Chorizo in bread",
      "Chorizo bread",
    ],
  },
  {
    id: 19,
    question: "Who wrote 'Wuthering Heights'?",
    correctAnswer: "Emily Brontë",
    options: [
      "Charlotte Brontë",
      "Jane Austen",
      "Emily Brontë",
      "Mary Shelley",
    ],
  },
  {
    id: 20,
    question: "What is the title of Jane Austen's first book?",
    correctAnswer: "'Sense and Sensibility'",
    options: [
      "'Sense and Sensibility'",
      "'Pride and Prejudice'",
      "'Emma'",
      "'Mansfield Park'",
    ],
  },
  {
    id: 21,
    question: "In what year was Google Images created?",
    correctAnswer: "2001",
    options: ["1999", "2001", "2003", "2005"],
  },
  {
    id: 22,
    question: "How many elements are there in the Periodic Table?",
    correctAnswer: "118",
    options: ["110", "118", "120", "126"],
  },
  {
    id: 23,
    question: "In a beer, what does the acronym IPA stand for?",
    correctAnswer: "Indian Pale Ale",
    options: [
      "Indian Pale Ale",
      "International Pale Ale",
      "India Pale Ale",
      "Indian Pilsner Ale",
    ],
  },
  {
    id: 24,
    question: "Who painted the Mona Lisa?",
    correctAnswer: "Leonardo da Vinci",
    options: [
      "Leonardo da Vinci",
      "Pablo Picasso",
      "Vincent van Gogh",
      "Michelangelo",
    ],
  },
  {
    id: 25,
    question: "What fruit has the scientific name Mangifera indica?",
    correctAnswer: "Mango",
    options: ["Mango", "Papaya", "Banana", "Orange"],
  },
  {
    id: 26,
    question: "What element of the periodic table has the symbol He?",
    correctAnswer: "Helium",
    options: ["Helium", "Hydrogen", "Iron", "Helium"],
  },
  {
    id: 27,
    question: "In what year was Salvador Dalí born?",
    correctAnswer: "1904",
    options: ["1899", "1904", "1910", "1915"],
  },
  {
    id: 28,
    question: "What planet is closest to the Sun?",
    correctAnswer: "Mercury",
    options: ["Venus", "Mercury", "Mars", "Jupiter"],
  },
  {
    id: 29,
    question: "Where was Joan Didion born?",
    correctAnswer: "Sacramento",
    options: ["Los Angeles", "San Francisco", "Sacramento", "New York"],
  },
  {
    id: 30,
    question: "Who was the first man to walk on the moon?",
    correctAnswer: "Neil Armstrong",
    options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Alan Shepard"],
  },
  {
    id: 31,
    question:
      "In which year was the National Autonomous University of Mexico (UNAM) founded?",
    correctAnswer: "1551",
    options: ["1521", "1551", "1600", "1700"],
  },
  {
    id: 32,
    question: "Who is the author of the work 'Don Quixote de la Mancha'?",
    correctAnswer: "Miguel de Cervantes",
    options: [
      "Miguel de Cervantes",
      "Luis de Góngora",
      "Fray Luis de León",
      "Garcilaso de la Vega",
    ],
  },
  {
    id: 33,
    question: "What mathematical symbol represents the square root?",
    correctAnswer: "√",
    options: ["√", "/", "π", "∑"],
  },
  {
    id: 34,
    question: "What is the Taj Mahal?",
    correctAnswer: "A mausoleum",
    options: ["A palace", "A mosque", "A mausoleum", "A church"],
  },
  {
    id: 35,
    question: "Who painted 'The Starry Night'?",
    correctAnswer: "Vincent van Gogh",
    options: [
      "Vincent van Gogh",
      "Claude Monet",
      "Pablo Picasso",
      "Edvard Munch",
    ],
  },
  {
    id: 36,
    question: "On which continent is the Sahara desert located?",
    correctAnswer: "Africa",
    options: ["Asia", "Africa", "South America", "Oceania"],
  },
  {
    id: 37,
    question: "Which country has the largest population in the world?",
    correctAnswer: "China",
    options: ["China", "India", "United States", "Indonesia"],
  },
  {
    id: 38,
    question: "In which country did sushi originate?",
    correctAnswer: "Japan",
    options: ["China", "Japan", "South Korea", "Thailand"],
  },
  {
    id: 39,
    question: "Who was the creator of the theory of relativity?",
    correctAnswer: "Albert Einstein",
    options: [
      "Isaac Newton",
      "Albert Einstein",
      "Galileo Galilei",
      "Niels Bohr",
    ],
  },
  {
    id: 40,
    question: "What is the longest river in the world?",
    correctAnswer: "The Amazon",
    options: ["The Nile", "The Amazon", "The Yangtze", "The Mississippi"],
  },
  {
    id: 41,
    question: "Which country is famous for its beer and chocolate?",
    correctAnswer: "Belgium",
    options: ["Belgium", "Germany", "France", "United Kingdom"],
  },
  {
    id: 42,
    question: "In which city is the Eiffel Tower located?",
    correctAnswer: "Paris",
    options: ["London", "Madrid", "Rome", "Paris"],
  },
  {
    id: 43,
    question: "Which planet is known as the 'red planet'?",
    correctAnswer: "Mars",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
  },
  {
    id: 44,
    question: "In what year did World War II end?",
    correctAnswer: "1945",
    options: ["1940", "1945", "1950", "1960"],
  },
  {
    id: 45,
    question: "What does the word 'pizza' mean in Italian?",
    correctAnswer: "Cake or pie",
    options: ["Cake or pie", "Round bread", "Sandwich", "Italian food"],
  },
  {
    id: 46,
    question:
      "What is the name of the famous wall that divided Berlin during the Cold War?",
    correctAnswer: "The Berlin Wall",
    options: [
      "The Berlin Wall",
      "The Moscow Wall",
      "The Vienna Wall",
      "The Hamburg Wall",
    ],
  },
  {
    id: 47,
    question: "What chemical element has the symbol O?",
    correctAnswer: "Oxygen",
    options: ["Oxygen", "Gold", "Osmium", "Ozone"],
  },
  {
    id: 48,
    question: "What is the capital of Egypt called?",
    correctAnswer: "Cairo",
    options: ["Tunis", "Rabat", "Cairo", "Algiers"],
  },
  {
    id: 49,
    question: "Who wrote 'One Hundred Years of Solitude'?",
    correctAnswer: "Gabriel García Márquez",
    options: [
      "Gabriel García Márquez",
      "Mario Vargas Llosa",
      "Carlos Fuentes",
      "Julio Cortázar",
    ],
  },
  {
    id: 50,
    question: "What is the largest continent in the world?",
    correctAnswer: "Asia",
    options: ["Asia", "Africa", "America", "Europe"],
  },
  {
    id: 51,
    question: "What animal is known as the king of the jungle?",
    correctAnswer: "Lion",
    options: ["Lion", "Tiger", "Elephant", "Jaguar"],
  },
  {
    id: 52,
    question: "In what country did the tango originate?",
    correctAnswer: "Argentina",
    options: ["Argentina", "Brazil", "Uruguay", "Chile"],
  },
  {
    id: 53,
    question: "What city is known as the 'Eternal City'?",
    correctAnswer: "Rome",
    options: ["Rome", "Athens", "Paris", "Madrid"],
  },
  {
    id: 54,
    question: "Who was the first president of the United States?",
    correctAnswer: "George Washington",
    options: [
      "George Washington",
      "Thomas Jefferson",
      "Abraham Lincoln",
      "John Adams",
    ],
  },
  {
    id: 55,
    question: "Which country invented football?",
    correctAnswer: "England",
    options: ["Brazil", "Argentina", "England", "Spain"],
  },
  {
    id: 56,
    question: "In which year was the first Star Wars movie released?",
    correctAnswer: "1977",
    options: ["1977", "1980", "1990", "2000"],
  },
  {
    id: 57,
    question: "Who painted the 'Mona Lisa'?",
    correctAnswer: "Leonardo da Vinci",
    options: [
      "Leonardo da Vinci",
      "Pablo Picasso",
      "Michelangelo",
      "Vincent van Gogh",
    ],
  },
  {
    id: 58,
    question: "What type of animal is a dolphin?",
    correctAnswer: "Mammal",
    options: ["Fish", "Reptiles", "Mammal", "Amphibian"],
  },
  {
    id: 59,
    question:
      "Which country is formed by a series of islands called an archipelago?",
    correctAnswer: "Japan",
    options: ["Japan", "Sweden", "Australia", "Greece"],
  },
  {
    id: 60,
    question: "Which country has the largest number of pyramids?",
    correctAnswer: "Sudan",
    options: ["Egypt", "Mexico", "Sudan", "Peru"],
  },
];
