<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\scena.glb -T --draco /draco/
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf, Edges, Outlines } from "@threlte/extras";

  import { AutoColliders } from "@threlte/rapier";

  export const ref = new Group();

  const gltf = useGltf("/scena-transformed.glb", { useDraco: "/draco/" });

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.snownam.geometry}
      material={gltf.materials["Material_0.012"]}
      position={[-2.57, 0.67, 3.62]}
      rotation={[0, 0.44, 0]}
      scale={0.69}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle.geometry}
      material={gltf.nodes.Circle.material}
    />

    <AutoColliders shape={"trimesh"}>
      <T.Mesh
        geometry={gltf.nodes.Ground.geometry}
        material={gltf.nodes.Ground.material}
      />
    </AutoColliders>

    <AutoColliders shape={"cuboid"}>
      <T.Mesh
        geometry={gltf.nodes.Pared.geometry}
        material={gltf.materials["Material.011"]}
        position={[0, 0.38, 0]}
      >
        <Outlines color="white" />
        <Outlines color="hotpink" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
    </AutoColliders>

    <T.Mesh
      geometry={gltf.nodes.sled_4.geometry}
      material={gltf.materials["Material_0.001"]}
      position={[-8.7, 0.55, -10.08]}
    />
    <T.Mesh
      geometry={gltf.nodes.Arbolm_7.geometry}
      material={gltf.materials["Material_0.002"]}
      position={[-14.03, 1.88, 4.93]}
    />
    <T.Mesh
      geometry={gltf.nodes.Arbolm_1.geometry}
      material={gltf.materials["Material_0.002"]}
      position={[-9.06, 1.88, 14.44]}
    />
    <T.Mesh
      geometry={gltf.nodes.Arbolm_2.geometry}
      material={gltf.materials["Material_0.002"]}
      position={[13.68, 1.88, 5.82]}
    />
    <T.Mesh
      geometry={gltf.nodes.Arbolm_3.geometry}
      material={gltf.materials["Material_0.002"]}
      position={[13.64, 1.85, -5.52]}
    />
    <T.Mesh
      geometry={gltf.nodes.Arbolm_4.geometry}
      material={gltf.materials["Material_0.002"]}
      position={[9.39, 2.32, -14.86]}
    />
    <T.Mesh
      geometry={gltf.nodes.Arbolm_5.geometry}
      material={gltf.materials["Material_0.002"]}
      position={[-8.85, 1.92, -14.86]}
    />
    <T.Mesh
      geometry={gltf.nodes.Arbolm_6.geometry}
      material={gltf.materials["Material_0.002"]}
      position={[-14.9, 1.84, -4.98]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0011.geometry}
      material={gltf.materials["Material_0.009"]}
      position={[-1.35, 0.4, 4.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh_0015.geometry}
      material={gltf.materials["Material_0.007"]}
      position={[-1.66, 0.53, 3.73]}
    />
    <T.Mesh
      geometry={gltf.nodes.Granroca.geometry}
      material={gltf.materials["Material_0.008"]}
      position={[0.23, 3.88, -17.5]}
    >
      <!-- <Edges thresholdAngle={20} color="white" scale={1.01} /> -->
      <!-- <Outlines color="white" thickness={0.02} /> -->
    </T.Mesh>

    <T.Mesh
      geometry={gltf.nodes.Mesh_0017.geometry}
      material={gltf.materials["Material_0.009"]}
      position={[-1.02, 0.4, 3.99]}
    />

    <T.Mesh
      geometry={gltf.nodes.boln_1.geometry}
      material={gltf.materials["Material.012"]}
      position={[-5.77, 0.41, 13.95]}
    >
      <Edges thresholdAngle={20} color="white" scale={1.01} />
      <Outlines color="white" thickness={0.02} />
    </T.Mesh>

    <T.Mesh
      geometry={gltf.nodes.Boln_3.geometry}
      material={gltf.materials["Material.012"]}
      position={[-12.37, 0.42, 6.71]}
    >
      <Edges thresholdAngle={20} color="white" scale={1.01} />
      <Outlines color="white" thickness={0.02} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Boln_5.geometry}
      material={gltf.materials["Material.012"]}
      position={[-3.54, 0.43, -2.13]}
    >
      <Edges thresholdAngle={20} color="white" scale={1.01} />
      <Outlines color="white" thickness={0.02} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Boln_2.geometry}
      material={gltf.materials["Material.012"]}
      position={[3.5, 0.43, 2.23]}
    >
      <Edges thresholdAngle={20} color="white" scale={1.01} />
      <Outlines color="white" thickness={0.02} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Boln_4.geometry}
      material={gltf.materials["Material.012"]}
      position={[11.29, 0.43, 6.66]}
    >
      <Edges thresholdAngle={20} color="white" scale={1.01} />
      <Outlines color="white" thickness={0.02} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Boln_6.geometry}
      material={gltf.materials["Material.012"]}
      position={[8.83, 0.43, -9.89]}
    >
      <Edges thresholdAngle={20} color="white" scale={1.01} />
      <Outlines color="white" thickness={0.02} />
    </T.Mesh>

    <T.Mesh
      geometry={gltf.nodes.Casa_4.geometry}
      material={gltf.materials["Material.009"]}
      position={[-12, 3.15, 10]}
    >
      <Outlines color="white" />
      <Outlines color="green" thickness={0.05} />
      <Outlines color="yellow" thickness={0.1} />
    </T.Mesh>

    <T.Mesh
      geometry={gltf.nodes.Casa_2.geometry}
      material={gltf.materials["Material.009"]}
      position={[12, 3.15, -10]}
    >
      <Outlines color="white" />
      <Outlines color="red" thickness={0.05} />
      <Outlines color="yellow" thickness={0.1} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Casa_3.geometry}
      material={gltf.materials["Material.010"]}
      position={[-12, 2.35, -10]}
    >
      <Outlines color="white" />
      <Outlines color="purple" thickness={0.05} />
      <Outlines color="yellow" thickness={0.1} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Casa_1.geometry}
      material={gltf.materials["Material.010"]}
      position={[12.01, 2.33, 10]}
    >
      <Outlines color="white" />
      <Outlines color="cyan" thickness={0.05} />
      <Outlines color="yellow" thickness={0.1} />
    </T.Mesh>

    <T.Group position={[-0.56, 0.47, 4.4]}>
      <T.Mesh
        geometry={gltf.nodes.Cube003_1.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube003_2.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube003_3.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube003_4.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[-3.24, 0.47, 3.01]}>
      <T.Mesh
        geometry={gltf.nodes.Cube005_1.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube005_2.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube005_3.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube005_4.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[1.18, 1.24, 3.29]}>
      <T.Mesh
        geometry={gltf.nodes.Cube006_1.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_2.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_3.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_4.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[3.43, 1.18, 0.57]}>
      <T.Mesh
        geometry={gltf.nodes.Cube007_1.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube007_2.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube007_3.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube007_4.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[-3.33, 1.24, -0.44]}>
      <T.Mesh
        geometry={gltf.nodes.Cube010_1.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube010_2.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube010_3.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube010_4.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[0.03, 1.18, -3.45]}>
      <T.Mesh
        geometry={gltf.nodes.Cube009_1.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube009_2.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube009_3.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube009_4.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[-3.48, 0.32, 3.66]}>
      <T.Mesh
        geometry={gltf.nodes.Cube013.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube013_1.geometry}
        material={gltf.materials["Material.022"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube013_2.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group position={[0.24, 0.32, 4.44]}>
      <T.Mesh
        geometry={gltf.nodes.Cube012_1.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube012_2.geometry}
        material={gltf.materials["Material.022"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube012_3.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group position={[-10.97, 0.44, -7.51]}>
      <T.Mesh
        geometry={gltf.nodes.Cube018_1.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube018_2.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube018_3.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube018_4.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[9.92, 0.47, 7.01]}>
      <T.Mesh
        geometry={gltf.nodes.Cube019_1.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube019_2.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube019_3.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube019_4.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[10.3, 0.32, 7.71]}>
      <T.Mesh
        geometry={gltf.nodes.Cube020.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube020_1.geometry}
        material={gltf.materials["Material.022"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube020_2.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group position={[-5.69, 0.45, 11.37]}>
      <T.Mesh
        geometry={gltf.nodes.Cube021.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube021_1.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube021_2.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube021_3.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[-5.98, 0.3, 12.11]}>
      <T.Mesh
        geometry={gltf.nodes.Cube022.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube022_1.geometry}
        material={gltf.materials["Material.022"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube022_2.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Group position={[12.33, 0.47, -1.96]}>
      <T.Mesh
        geometry={gltf.nodes.Cube023.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube023_1.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube023_2.geometry}
        material={gltf.materials["Material.019"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube023_3.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[12.71, 0.32, -1.26]}>
      <T.Mesh
        geometry={gltf.nodes.Cube024.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube024_1.geometry}
        material={gltf.materials["Material.022"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube024_2.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.sled_1.geometry}
      material={gltf.materials["Material_0.001"]}
      position={[-8.97, 0.55, 7.44]}
    />
    <T.Mesh
      geometry={gltf.nodes.sled_2.geometry}
      material={gltf.materials["Material_0.001"]}
      position={[8, 0.55, 10.3]}
    />
    <T.Mesh
      geometry={gltf.nodes.sled_3.geometry}
      material={gltf.materials["Material_0.001"]}
      position={[11.59, 0.55, -0.4]}
    />

    <!-- Pinos -->

    <T.Group position={[-7.07, 1.86, 10.7]}>
      <T.Mesh
        geometry={gltf.nodes.Circle007.geometry}
        material={gltf.materials["Material.016"]}
      >
        <Outlines color="white" />
        <Outlines color="cyan" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_1.geometry}
        material={gltf.materials["Material.013"]}
      >
        <Outlines color="white" />
        <Outlines color="green" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_2.geometry}
        material={gltf.materials["Material.015"]}
      />
    </T.Group>
    <T.Group position={[0, 4, 0]} scale={2.16}>
      <T.Mesh
        geometry={gltf.nodes.Circle007.geometry}
        material={gltf.materials["Material.016"]}
      >
        <Outlines color="white" />
        <Outlines color="cyan" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_1.geometry}
        material={gltf.materials["Material.013"]}
      >
        <Outlines color="white" />
        <Outlines color="green" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_2.geometry}
        material={gltf.materials["Material.015"]}
      />
    </T.Group>
    <T.Group position={[8.18, 1.86, 13.44]}>
      <T.Mesh
        geometry={gltf.nodes.Circle007.geometry}
        material={gltf.materials["Material.016"]}
      >
        <Outlines color="white" />
        <Outlines color="cyan" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_1.geometry}
        material={gltf.materials["Material.013"]}
      >
        <Outlines color="white" />
        <Outlines color="green" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_2.geometry}
        material={gltf.materials["Material.015"]}
      />
    </T.Group>
    <T.Group position={[13.78, 1.86, -2.31]}>
      <T.Mesh
        geometry={gltf.nodes.Circle007.geometry}
        material={gltf.materials["Material.016"]}
      >
        <Outlines color="white" />
        <Outlines color="cyan" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_1.geometry}
        material={gltf.materials["Material.013"]}
      >
        <Outlines color="white" />
        <Outlines color="green" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_2.geometry}
        material={gltf.materials["Material.015"]}
      />
    </T.Group>
    <T.Group position={[6.38, 1.86, -9.75]}>
      <T.Mesh
        geometry={gltf.nodes.Circle007.geometry}
        material={gltf.materials["Material.016"]}
      >
        <Outlines color="white" />
        <Outlines color="cyan" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_1.geometry}
        material={gltf.materials["Material.013"]}
      >
        <Outlines color="white" />
        <Outlines color="green" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_2.geometry}
        material={gltf.materials["Material.015"]}
      />
    </T.Group>
    <T.Group position={[-12.03, 1.86, -5.35]}>
      <T.Mesh
        geometry={gltf.nodes.Circle007.geometry}
        material={gltf.materials["Material.016"]}
      >
        <Outlines color="white" />
        <Outlines color="cyan" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_1.geometry}
        material={gltf.materials["Material.013"]}
      >
        <Outlines color="white" />
        <Outlines color="green" thickness={0.05} />
        <Outlines color="yellow" thickness={0.1} />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Circle007_2.geometry}
        material={gltf.materials["Material.015"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.tronco_1.geometry}
      material={gltf.materials["Material_0.010"]}
      position={[10.42, 0.25, 11.25]}
    />
    <T.Mesh
      geometry={gltf.nodes.tronco_2.geometry}
      material={gltf.materials["Material_0.010"]}
      position={[12.47, 0.31, -8.02]}
    />
    <T.Mesh
      geometry={gltf.nodes.tronco_3.geometry}
      material={gltf.materials["Material_0.010"]}
      position={[-10.2, 0.27, -10.77]}
    />
    <T.Mesh
      geometry={gltf.nodes.tronco_4.geometry}
      material={gltf.materials["Material_0.010"]}
      position={[-9.56, 0.31, 9.86]}
    />
    <T.Mesh
      geometry={gltf.nodes.Boln_7.geometry}
      material={gltf.materials["Material.012"]}
      position={[2.44, 0.43, -3.54]}
    >
      <Edges thresholdAngle={20} color="white" scale={1.01} />
      <Outlines color="white" thickness={0.02} />
    </T.Mesh>

    <T.Mesh
      geometry={gltf.nodes.NurbsPath.geometry}
      material={gltf.nodes.NurbsPath.material}
      position={[0, 4, 15]}
    >
      <Outlines color="white" />
      <Outlines color="yellow" thickness={0.05} />
      <Outlines color="orange" thickness={0.1} />
    </T.Mesh>

    <AutoColliders shape={"cuboid"}>
      <T.Mesh
        geometry={gltf.nodes.Plane003.geometry}
        material={gltf.nodes.Plane003.material}
        position={[5, 0, 0]}
        scale={[0.2, 0.3, 0.2]}
      >
        <Outlines color="white" />
        <Outlines color="yellow" thickness={0.05} />
        <Outlines color="orange" thickness={0.1} />
      </T.Mesh>
    </AutoColliders>

    <AutoColliders shape={"cuboid"}>
      <T.Mesh
        geometry={gltf.nodes.Plane004.geometry}
        material={gltf.nodes.Plane004.material}
        position={[-5, 0, 0]}
        scale={[0.2, 0.3, 0.2]}
      >
        <Outlines color="white" />
        <Outlines color="yellow" thickness={0.05} />
        <Outlines color="orange" thickness={0.1} />
      </T.Mesh>
    </AutoColliders>
    <T.Group position={[3.52, 1.15, -0.18]}>
      <T.Mesh
        geometry={gltf.nodes.BézierCircle008.geometry}
        material={gltf.materials["Material.027"]}
      />
      <T.Mesh
        geometry={gltf.nodes.BézierCircle008_1.geometry}
        material={gltf.materials["Material.025"]}
      />
      <T.Mesh
        geometry={gltf.nodes.BézierCircle008_2.geometry}
        material={gltf.materials["Material.026"]}
      />
    </T.Group>
    <T.Group position={[-0.68, 1.11, -3.51]}>
      <T.Mesh
        geometry={gltf.nodes.BézierCircle010.geometry}
        material={gltf.materials["Material.027"]}
      />
      <T.Mesh
        geometry={gltf.nodes.BézierCircle010_1.geometry}
        material={gltf.materials["Material.025"]}
      />
      <T.Mesh
        geometry={gltf.nodes.BézierCircle010_2.geometry}
        material={gltf.materials["Material.026"]}
      />
    </T.Group>
    <T.Group position={[-3.29, 1.12, 0.5]}>
      <T.Mesh
        geometry={gltf.nodes.BézierCircle011.geometry}
        material={gltf.materials["Material.027"]}
      />
      <T.Mesh
        geometry={gltf.nodes.BézierCircle011_1.geometry}
        material={gltf.materials["Material.025"]}
      />
      <T.Mesh
        geometry={gltf.nodes.BézierCircle011_2.geometry}
        material={gltf.materials["Material.026"]}
      />
    </T.Group>
    <T.Group position={[-10.92, 0.33, -6.57]}>
      <T.Mesh
        geometry={gltf.nodes.BézierCircle012.geometry}
        material={gltf.materials["Material.027"]}
      />
      <T.Mesh
        geometry={gltf.nodes.BézierCircle012_1.geometry}
        material={gltf.materials["Material.025"]}
      />
      <T.Mesh
        geometry={gltf.nodes.BézierCircle012_2.geometry}
        material={gltf.materials["Material.026"]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
