<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\snoo.glb -T --draco /draco/
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/snoo-transformed.glb', { useDraco: '/draco/' })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh position={[2.3, 4, 1]} rotation={[0, 0, -1]} geometry={gltf.nodes.Head_Collapsed.geometry} material={gltf.materials['Material.030']} />
    <T.Mesh position={[-2.3, 4, 1]} rotation={[0, 0, 1]} geometry={gltf.nodes.Head_Collapsed.geometry} material={gltf.materials['Material.030']} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>

